export const WORDPRESS_SERVICES = [
  {
    id: 'wordpress-development',
    title: 'WordPress Website Development',
    description: 'Get a professional website that converts. Build your business presence with a custom WordPress site — from landing pages to full corporate websites that rank and sell.',
    icon: 'Globe',
    priceRange: '$1,000 – $3,500',
    features: [
      'Custom WordPress website development',
      'Business websites (5–10 pages)',
      'Landing pages',
      'Blog websites',
      'Corporate websites',
    ],
    tools: ['WordPress', 'Elementor', 'Divi', 'WPBakery Page Builder'],
  },
  {
    id: 'speed-optimization',
    title: 'WordPress Speed Optimization',
    description: 'Slow site killing your rankings? Fix it. Boost your page speed, nail Core Web Vitals, and watch your SEO scores and conversion rates improve.',
    icon: 'Zap',
    priceRange: '$250 – $750',
    features: [
      'Page load speed optimization',
      'Core Web Vitals',
      'Database cleanup',
      'Image optimization',
      'CDN integration',
    ],
    tools: ['Cloudflare', 'Redis', 'LiteSpeed Cache'],
  },
  {
    id: 'server-migration',
    title: 'WordPress Server Migration',
    description: 'Ready to upgrade your hosting? Move your site with zero downtime — from shared hosting to VPS, cPanel to cloud. No stress, no data loss.',
    icon: 'Server',
    priceRange: '$200 – $600',
    features: [
      'Shared hosting → VPS',
      'cPanel → Cloud server',
      'Local → production',
    ],
    tools: ['Amazon Web Services', 'DigitalOcean', 'Linode'],
  },
  {
    id: 'security-hardening',
    title: 'WordPress Security Hardening',
    description: 'Don\'t leave your site vulnerable. Get malware removal, firewall setup, login protection, and a full security audit — so you can sleep at night.',
    icon: 'Shield',
    priceRange: '$200 – $550',
    features: [
      'Malware removal',
      'Firewall setup',
      'Login protection',
      'Security audit',
    ],
    tools: ['Cloudflare', 'Wordfence'],
  },
  {
    id: 'maintenance-support',
    title: 'WordPress Maintenance & Support',
    description: 'Stop worrying about updates and downtime. Get DevOps-grade monitoring, backups, and updates — so your site stays fast, secure, and always online.',
    icon: 'Settings',
    priceRange: '$150 – $350 / month',
    features: [
      'Plugin updates',
      'Backups',
      'Security checks',
      'Uptime monitoring',
      'Bug fixes',
    ],
    tools: ['Prometheus', 'Grafana', 'Uptime Kuma'],
  },
  {
    id: 'devops-setup',
    title: 'DevOps Setup for WordPress',
    description: 'Scale with confidence. Dockerized deployments, CI/CD pipelines, and staging environments — so you can deploy changes without risk.',
    icon: 'Layers',
    priceRange: '$800 – $2,500',
    features: [
      'Dockerized WordPress deployment',
      'CI/CD pipelines',
      'Staging environments',
      'Automated backups',
    ],
    tools: ['Docker', 'Kubernetes'],
  },
  {
    id: 'performance-infrastructure',
    title: 'WordPress Performance Infrastructure',
    description: 'Ready for enterprise-level performance? CDN architecture, Redis cache, load balancing — built for sites that handle real traffic.',
    icon: 'Cpu',
    priceRange: '$1,500 – $4,500',
    features: [
      'CDN architecture',
      'Redis object cache',
      'Load balancing',
      'Server optimization',
    ],
    tools: ['Nginx', 'Redis', 'Amazon Web Services'],
  },
  {
    id: 'bug-fixing',
    title: 'WordPress Bug Fixing',
    description: 'Site broken? Fix it fast. Plugin conflicts, broken layouts, PHP errors, theme issues — resolved quickly so you can get back to business.',
    icon: 'Wrench',
    priceRange: '$75 – $250',
    features: [
      'Plugin conflict resolution',
      'Broken layouts',
      'PHP errors',
      'Theme issues',
    ],
    tools: [],
  },
  {
    id: 'website-audit',
    title: 'WordPress Website Audit',
    description: 'Not sure what\'s wrong with your site? Get a clear picture. Performance review, SEO issues, security risks, and UX improvements — with actionable next steps.',
    icon: 'Search',
    priceRange: '$75 – $225',
    features: [
      'Performance review',
      'SEO issues',
      'Security risks',
      'UX improvements',
    ],
    tools: [],
  },
  {
    id: 'hosting-setup',
    title: 'Website Hosting Setup',
    description: 'Hosting confusion holding you back? Get cPanel, hPanel, shared, or VPS — with domain, SSL, backups, and monitoring done right.',
    icon: 'Cloud',
    priceRange: '$200 – $600',
    features: [
      'cPanel, hPanel, shared & VPS hosting setup',
      'Domain + SSL configuration',
      'Backups & monitoring',
    ],
    tools: ['cPanel', 'hPanel', 'Amazon Web Services', 'DigitalOcean', 'Linode'],
  },
] as const;

export const SERVICE_PACKAGES = [
  {
    id: 'starter-website',
    name: 'Starter Website',
    price: '$1,500',
    period: 'one-time',
    description: 'Launch your online presence. Everything you need to get started.',
    features: [
      'WordPress website',
      'Speed optimization',
      'SEO basics',
    ],
    popular: false,
  },
  {
    id: 'business-website',
    name: 'Business Website',
    price: '$2,800',
    period: 'one-time',
    description: 'Scale your business with a site that performs and converts.',
    features: [
      'Custom design',
      'Performance optimization',
      'CDN + caching',
      'Security setup',
    ],
    popular: true,
  },
  {
    id: 'premium-infrastructure',
    name: 'Premium Infrastructure Website',
    price: '$4,500+',
    period: 'project-based',
    description: 'Enterprise-grade setup for sites that can\'t afford to slow down.',
    features: [
      'WordPress development',
      'Server optimization',
      'Monitoring system',
      'CDN setup',
    ],
    popular: false,
  },
] as const;
