export const WORDPRESS_SERVICES = [
  {
    id: 'wordpress-development',
    title: 'WordPress Website Development',
    description: 'Your core service. Custom WordPress websites built with Elementor, Divi, or WPBakery — business sites, landing pages, blogs, and corporate websites.',
    icon: 'Globe',
    priceRange: '$1,000 – $3,500',
    features: [
      'Custom WordPress website development',
      'Business websites (5–10 pages)',
      'Landing pages',
      'Blog websites',
      'Corporate websites',
    ],
    tools: ['WordPress', 'Elementor', 'Divi', 'WPBakery Page Builder'],
  },
  {
    id: 'speed-optimization',
    title: 'WordPress Speed Optimization',
    description: 'High-demand service. Optimize page load speed, Core Web Vitals, and database performance for better SEO and conversions.',
    icon: 'Zap',
    priceRange: '$250 – $750',
    features: [
      'Page load speed optimization',
      'Core Web Vitals',
      'Database cleanup',
      'Image optimization',
      'CDN integration',
    ],
    tools: ['Cloudflare', 'Redis', 'LiteSpeed Cache'],
  },
  {
    id: 'server-migration',
    title: 'WordPress Server Migration',
    description: 'Leverage server and DevOps knowledge. Seamless migration with zero downtime — shared hosting to VPS, cPanel to cloud.',
    icon: 'Server',
    priceRange: '$200 – $600',
    features: [
      'Shared hosting → VPS',
      'cPanel → Cloud server',
      'Local → production',
    ],
    tools: ['Amazon Web Services', 'DigitalOcean', 'Linode'],
  },
  {
    id: 'security-hardening',
    title: 'WordPress Security Hardening',
    description: 'Protect your site from threats. Malware removal, firewall setup, login protection, and comprehensive security audits.',
    icon: 'Shield',
    priceRange: '$200 – $550',
    features: [
      'Malware removal',
      'Firewall setup',
      'Login protection',
      'Security audit',
    ],
    tools: ['Cloudflare', 'Wordfence'],
  },
  {
    id: 'maintenance-support',
    title: 'WordPress Maintenance & Support',
    description: 'Profitable long-term. DevOps-grade monitoring with Prometheus, Grafana, and Uptime Kuma for peace of mind.',
    icon: 'Settings',
    priceRange: '$150 – $350 / month',
    features: [
      'Plugin updates',
      'Backups',
      'Security checks',
      'Uptime monitoring',
      'Bug fixes',
    ],
    tools: ['Prometheus', 'Grafana', 'Uptime Kuma'],
  },
  {
    id: 'devops-setup',
    title: 'DevOps Setup for WordPress',
    description: 'Very few WordPress developers offer this. Dockerized deployments, CI/CD pipelines, and staging environments.',
    icon: 'Layers',
    priceRange: '$800 – $2,500',
    features: [
      'Dockerized WordPress deployment',
      'CI/CD pipelines',
      'Staging environments',
      'Automated backups',
    ],
    tools: ['Docker', 'Kubernetes'],
  },
  {
    id: 'performance-infrastructure',
    title: 'WordPress Performance Infrastructure',
    description: 'High-end service for serious businesses. CDN architecture, Redis cache, load balancing, and server optimization.',
    icon: 'Cpu',
    priceRange: '$1,500 – $4,500',
    features: [
      'CDN architecture',
      'Redis object cache',
      'Load balancing',
      'Server optimization',
    ],
    tools: ['Nginx', 'Redis', 'Amazon Web Services'],
  },
  {
    id: 'bug-fixing',
    title: 'WordPress Bug Fixing',
    description: 'Very popular on freelance platforms. Quick resolution of plugin conflicts, broken layouts, PHP errors, and theme issues.',
    icon: 'Wrench',
    priceRange: '$75 – $250',
    features: [
      'Plugin conflict resolution',
      'Broken layouts',
      'PHP errors',
      'Theme issues',
    ],
    tools: [],
  },
  {
    id: 'website-audit',
    title: 'WordPress Website Audit',
    description: 'Great for generating leads. Comprehensive review of performance, SEO, security, and UX with actionable recommendations.',
    icon: 'Search',
    priceRange: '$75 – $225',
    features: [
      'Performance review',
      'SEO issues',
      'Security risks',
      'UX improvements',
    ],
    tools: [],
  },
  {
    id: 'hosting-setup',
    title: 'Website Hosting Setup',
    description: 'Many clients struggle with hosting. cPanel, hPanel, shared hosting, or VPS — domain + SSL, backups, and monitoring.',
    icon: 'Cloud',
    priceRange: '$200 – $600',
    features: [
      'cPanel, hPanel, shared & VPS hosting setup',
      'Domain + SSL configuration',
      'Backups & monitoring',
    ],
    tools: ['cPanel', 'hPanel', 'Amazon Web Services', 'DigitalOcean', 'Linode'],
  },
] as const;

export const SERVICE_PACKAGES = [
  {
    id: 'starter-website',
    name: 'Starter Website',
    price: '$1,500',
    period: 'one-time',
    description: 'Perfect for small businesses and startups',
    features: [
      'WordPress website',
      'Speed optimization',
      'SEO basics',
    ],
    popular: false,
  },
  {
    id: 'business-website',
    name: 'Business Website',
    price: '$2,800',
    period: 'one-time',
    description: 'For growing businesses that need more',
    features: [
      'Custom design',
      'Performance optimization',
      'CDN + caching',
      'Security setup',
    ],
    popular: true,
  },
  {
    id: 'premium-infrastructure',
    name: 'Premium Infrastructure Website',
    price: '$4,500+',
    period: 'project-based',
    description: 'Complete infrastructure for serious businesses',
    features: [
      'WordPress development',
      'Server optimization',
      'Monitoring system',
      'CDN setup',
    ],
    popular: false,
  },
] as const;
